packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - better-sqlite3

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
