packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  sharp: true
  unrs-resolver: true

nodeLinker: hoisted

supportedArchitectures:
  os:
    - win32
    - darwin
    - linux
  cpu:
    - x64
    - arm64
